version: '3'

services:
  container1:
    image: linuxserver/wireguard  # Replace with the actual image you're using
    container_name: container1
    networks:
      - my_network
    command: tail -f /dev/null  # Keeps the container running

  container2:
    image: linuxserver/wireguard  # Replace with the actual image you're using
    container_name: container2
    networks:
      - my_network
    command: tail -f /dev/null  # Keeps the container running

networks:
  my_network:
    driver: bridge