FROM python:3.10-slim

RUN apt-get update && \
apt-get install -y build-essential && \
apt-get install -y wget && \
apt-get install -y curl && \
apt-get install -y git && \
apt-get install -y vim && \
apt-get install -y cmake && \
apt-get clean

RUN mkdir /Satori && \
cd /Satori && git clone -b dev https://github.com/SatoriNetwork/Synapse.git && \
cd /Satori && git clone -b dev https://github.com/SatoriNetwork/Lib.git && \
cd /Satori && git clone -b dev https://github.com/SatoriNetwork/Wallet.git && \
cd /Satori && git clone -b dev https://github.com/SatoriNetwork/Engine.git && \
cd /Satori && git clone -b dev https://github.com/SatoriNetwork/Neuron.git && \
cd /Satori && git clone https://github.com/amazon-science/chronos-forecasting.git && \
cd /Satori && git clone https://github.com/ibm-granite/granite-tsfm.git

ARG GPU_FLAG=off
ENV GPU_FLAG=${GPU_FLAG}
# for torch: cpu cu118 cu121 cu124 --index-url https://download.pytorch.org/whl/cpu
RUN pip install --upgrade pip && \
if [ "$GPU_FLAG" = "on" ]; then \
pip install --no-cache-dir torch==2.4.1 --index-url https://download.pytorch.org/whl/cu124; \
else \
pip install --no-cache-dir torch==2.4.1 --index-url https://download.pytorch.org/whl/cpu; \
fi && \
pip install --no-cache-dir transformers==4.44.2 && \
pip install --no-cache-dir /Satori/granite-tsfm && \
pip install --no-cache-dir /Satori/chronos-forecasting && \
cd /Satori/Synapse && pip install --no-cache-dir -r requirements.txt && python setup.py develop && \
cd /Satori/Lib && pip install --no-cache-dir -r requirements.txt && python setup.py develop && \
cd /Satori/Wallet && pip install --no-cache-dir -r requirements.txt && python setup.py develop && \
cd /Satori/Engine && pip install --no-cache-dir -r requirements.txt && python setup.py develop && \
cd /Satori/Neuron && pip install --no-cache-dir -r requirements.txt && python setup.py develop

# satori ui
EXPOSE 24601

WORKDIR /Satori/Neuron/satorineuron/web
CMD ["bash", "./start_from_image.sh"]
