headless: false
disable restart: false
neuron lock enabled: true
neuron lock hash: fs1f3se5ffsef1sf
mining mode: true
reward address: EZDfZiJcvx1Ymrj8otCeiY4eLfPsZkHri9
engine version: v2
logging level: debug
